server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/splitpay
    username: splitpay_user
    password: splitpay_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Optional Swagger config (if you later add SpringDoc)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Optional Redis placeholder for later
# spring:
#   redis:
#     host: localhost
#     port: 6379

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
